### ISSUE TITLE
同学你好，请问你的homework和lab是在哪找到的？

### ISSUE THREAD

**Issue by wuyuesong** [MartinLwx/Data100-Fall-2021-UCB#1]
同学你好，请问你的homework和lab是在哪找到的？我点那个lab好像要伯克利的账号呀。

**Comment by MartinLwx** [comment]
官方有维护一个仓库：https://github.com/DS-100/fa21   可以克隆到本地做～

**Comment by wuyuesong** [comment]
哦哦，好的，谢谢同学~
